general second pass refactoring and cleanup
general bash code sharing with libx.sh, and misc cleanups.  Further
cleanups will likely be smaller and more incremental than this second
pass wholesale cleanup.

diff --git a/tools/scripts/bs-check-tuv-el6 b/tools/scripts/bs-check-tuv-el6
--- a/tools/scripts/bs-check-tuv-el6
+++ b/tools/scripts/bs-check-tuv-el6
@@ -36,9 +36,9 @@
 #############################################################################
 #############################################################################
 ##
-## repochart-tuv-el6 \
-##     [<input>=${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise.6Superset.en.os.SRPMS.datesorted] \
-##     [<output>=${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise.6Superset.en.os.SRPMS.repochart]
+## bs-check-tuv-el6 \
+##     [<input>=${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise.6Superset.en.os.SRPMS.repochart] \
+##     [<output>=${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise.6Superset.en.os.SRPMS.repochart.{csv,html}]
 ##
 ##
 ## DESCRIPTION
@@ -60,14 +60,28 @@
 #############################################################################
 #############################################################################
 ##
-## get runtime environment
+## local constant definitions
 ##
-starttime="$( date +%Y-%m-%d--%H-%M-%S )"
-progname="$( basename $0 )"
-progdir=$( ( pushd $( dirname $( readlink -e $0 ) ) > /dev/null 2>&1 ; \
-    pwd ; popd > /dev/null 2>&1 ) )
-rundir="$( pwd )"
-mypid=$$
+
+# for common script library- libx.sh
+x_toolname="el-build"
+x_prefix=/usr
+
+
+#############################################################################
+#############################################################################
+##
+## load system library
+##
+
+if [ -f "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh" ]; then
+    source "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh"
+elif [ -f "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" ]; then 
+    source "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" 
+else
+    echo "$0: error: fatal: could not load ${x_toolname} system library libx.sh"
+    exit 1
+fi
 
 
 #############################################################################
@@ -76,11 +90,11 @@ mypid=$$
 ## constant and option default definitions
 ##
 
-# to enable debug messages
-debug=1
+# to enable debug messages if desired
+x_debug=0
 
-# to suppress status messages
-quiet=0
+# to suppress status messages if desired
+x_quiet=0
 
 
 #############################################################################
@@ -100,78 +114,12 @@ function usage {
 
 
 #############################################################################
-#
-# usage: status <message...>
-#
-# wrapper for sending status messages to console and log
-#
-# globals used: quiet, progname, logfiles(not required)
-#
-function status {
-    time="$( date +%Y-%m-%d.%H:%M:%S )"
-    if ((! $quiet)); then
-	echo "${progname}: ${time}: status: $@"
-    fi
-    for logfile in $logfiles; do
-	echo "${progname}: ${time}: status: $@" >> $logfile
-    done
-}
-
-#############################################################################
-#
-# usage: debug <message...>
-#
-# wrapper for sending debug messages to console and log
-#
-# globals used: debug, progname, logfiles(not required)
-#
-function debug {
-    time="$( date +%Y-%m-%d.%H:%M:%S )"
-    if (($debug)); then
-	echo "${progname}: ${time}: debug: $@"
-    fi
-    for logfile in $logfiles; do
-	echo "${progname}: ${time}: debug: $@" >> $logfile
-    done
-}
-
-
-#############################################################################
-#
-# usage: die <message...>
-#
-# issue last words
-#
-function die {
-    status "$@"
-    exit 1
-}
-
-
-#############################################################################
-#
-# usage: old_school_crypto <string>
-#
-# probably overkill avoidance of explicit TUV referencing
-#
-function old_school_crypto {
-    echo "$@" | tr 'a-zA-Z' 'n-za-mN-ZA-M'
-}
-
-
-#############################################################################
 #############################################################################
 ##
 ## main
 ##
 
 status "initializing..."
-
-
-#############################################################################
-### calculate tree root and set up environment
-elbuild_devroot=$( pushd "${progdir}/../.." > /dev/null 2>&1 ; \
-    pwd ; popd > /dev/null 2>&1 )
 
 
 if [ $# -eq 0 ]; then 
@@ -192,8 +140,16 @@ if [ ! -f "${input}" ]; then
 fi
 
 
-if [ -f "${output}" ]; then
-    die "output ${output} already exists"
+if [ -f "${output}.html" ]; then
+#    die "output ${output}.html already exists"
+    mv -f "${output}.html" \
+	 "${output}.html.backup.${starttime}"
+fi
+
+if [ -f "${output}.csv" ]; then
+#    die "output ${output}.html already exists"
+    mv -f "${output}.csv" \
+	 "${output}.csv.backup.${starttime}"
 fi
 
 tmpdir="/tmp/tmp.${progname}.xyz.${starttime}.$$"
@@ -258,7 +214,7 @@ while read line; do
     status "scanning #"$( cat "${tmpdir}/num_pkgs" | wc -l )"/${est_num_pkgs} : ${pkg_n} ..."
     # see if pkg should be in asc
     pkg_in_asc="no"
-    if ( ! grep -q "^===${pkg_n}===" "${elbuild_devroot}/Ascendos/6/6.0/configs/tuv-pkgs-not-in-asc6" ); then
+    if ( ! grep -q "^===${pkg_n}===" "${x_devdir}/6/6.0/configs/tuv-pkgs-not-in-asc6" ); then
 	pkg_in_asc="yes"
 	echo "${pkg_nvr}" >> "${tmpdir}/num_pkgs_in_asc"
     fi
@@ -319,11 +275,47 @@ while read line; do
     echo -en "\"${pkg_nvr}\"," >> "${output}.csv"
     echo -en "\"${pkg_time_date}\"," >> "${output}.csv"
     echo -en "\"${pkg_in_asc}\"," >> "${output}.csv"
-    echo -en "\"${pkg_exists_in_bs}\"," >> "${output}.csv"
-    echo -en "\"${pkg_complete_in_bs}\"," >> "${output}.csv"
+    if [ "${pkg_in_asc}" == "no" ]; then
+	echo -en "\"n/a\"," >> "${output}.csv"
+	echo -en "\"n/a\"," >> "${output}.csv"
+    else
+	pkg_nvr_minus_el6suffix=$( echo "${pkg_nvr}" | sed -e 's/\.el6.*$//' )
+	status "pkg_nvr_minus_el6suffix is ${pkg_nvr_minus_el6suffix} ..."
+	if [ -d "${x_devdir}/packages/${pkg_nvr}" ]; then
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	elif [ -d "${x_devdir}/packages/${pkg_nv}" ]; then
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	elif [ -d "${x_devdir}/packages/${pkg_n}" ]; then
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	elif [ -d "${x_devdir}/packages/${pkg_nvr_minus_el6suffix}" ]; then
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	    echo -en "\"fixme\"," >> "${output}.csv"
+	else
+	    if [ "${pkg_exists_in_bs}" == "no" ]; then
+		echo -en "\"<b>NO</b>\"," >> "${output}.csv"
+	    else
+		echo -en "\"${pkg_exists_in_bs}\"," >> "${output}.csv"
+	    fi
+	    if [ "${pkg_complete_in_bs}" == "no" ]; then
+		echo -en "\"<b>NO</b>\"," >> "${output}.csv"
+	    else
+		echo -en "\"${pkg_complete_in_bs}\"," >> "${output}.csv"
+	    fi
+	fi
+    fi
+    # end if pkg_in_asc else ...
+
     echo -en "${in_repo_status_csv}" >> "${output}.csv"
-    echo -en "\"${build_target}\"," >> "${output}.csv"
-    echo -en "\"${tags}\"," >> "${output}.csv"
+    if [ "${pkg_in_asc}" == "no" ]; then
+	echo -en "\"n/a\"," >> "${output}.csv"
+	echo -en "\"n/a\"," >> "${output}.csv"
+    else
+	echo -en "\"${build_target}\"," >> "${output}.csv"
+	echo -en "\"${tags}\"," >> "${output}.csv"
+    fi
     echo -en "\n" >> "${output}.csv"
 
 done < "${tmpdir}/revinput"
@@ -352,10 +344,12 @@ echo -en "\n" >> "${output}.csv"
 cp "${output}.csv" "${tmpdir}/pkg_big_board.csv"
 
 pushd "${tmpdir}" 2>&1 > /dev/null
-"${elbuild_devroot}/Ascendos/tools/csv2html.pl" \
+"${x_devdir}/tools/scripts/csv2html.pl" \
     -b -e -d \
     -i "pkg_big_board.csv" \
-    -o "pkg_big_board.html"
+    -o "pkg_big_board.html" \
+    -t "PackageBigBoard" \
+    > "${tmpdir}/csv2html.out" 2>&1
 popd "${tmpdir}" 2>&1 > /dev/null
 
 mv "${tmpdir}/pkg_big_board.html" "${output}.html"
diff --git a/tools/scripts/datesort-tuv-el6-srpms b/tools/scripts/datesort-tuv-el6-srpms
--- a/tools/scripts/datesort-tuv-el6-srpms
+++ b/tools/scripts/datesort-tuv-el6-srpms
@@ -61,14 +61,28 @@
 #############################################################################
 #############################################################################
 ##
-## get runtime environment
+## local constant definitions
 ##
-starttime="$( date +%Y-%m-%d--%H-%M-%S )"
-progname="$( basename $0 )"
-progdir=$( ( pushd $( dirname $( readlink -e $0 ) ) > /dev/null 2>&1 ; \
-    pwd ; popd > /dev/null 2>&1 ) )
-rundir="$( pwd )"
-mypid=$$
+
+# for common script library- libx.sh
+x_toolname="el-build"
+x_prefix=/usr
+
+
+#############################################################################
+#############################################################################
+##
+## load system library
+##
+
+if [ -f "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh" ]; then
+    source "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh"
+elif [ -f "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" ]; then 
+    source "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" 
+else
+    echo "$0: error: fatal: could not load ${x_toolname} system library libx.sh"
+    exit 1
+fi
 
 
 #############################################################################
@@ -76,6 +90,13 @@ mypid=$$
 ##
 ## constant and option default definitions
 ##
+
+# to enable debug messages if desired
+x_debug=0
+
+# to suppress status messages if desired
+x_quiet=0
+
 
 # excessive and/or amusing vendor name use avoidance
 tuv_name_lc_enc="erqung"
@@ -86,12 +107,6 @@ flavors="\
 6ComputeNode
 6Client
 "
-
-# to enable debug messages
-debug=1
-
-# to suppress status messages
-quiet=0
 
 
 #############################################################################
@@ -107,66 +122,6 @@ function usage {
     echo ""
     echo ""
     exit 1
-}
-
-
-#############################################################################
-#
-# usage: status <message...>
-#
-# wrapper for sending status messages to console and log
-#
-# globals used: quiet, progname, logfiles(not required)
-#
-function status {
-    time="$( date +%Y-%m-%d.%H:%M:%S )"
-    if ((! $quiet)); then
-	echo "${progname}: ${time}: status: $@"
-    fi
-    for logfile in $logfiles; do
-	echo "${progname}: ${time}: status: $@" >> $logfile
-    done
-}
-
-#############################################################################
-#
-# usage: debug <message...>
-#
-# wrapper for sending debug messages to console and log
-#
-# globals used: debug, progname, logfiles(not required)
-#
-function debug {
-    time="$( date +%Y-%m-%d.%H:%M:%S )"
-    if (($debug)); then
-	echo "${progname}: ${time}: debug: $@"
-    fi
-    for logfile in $logfiles; do
-	echo "${progname}: ${time}: debug: $@" >> $logfile
-    done
-}
-
-
-#############################################################################
-#
-# usage: die <message...>
-#
-# issue last words
-#
-function die {
-    status "$@"
-    exit 1
-}
-
-
-#############################################################################
-#
-# usage: old_school_crypto <string>
-#
-# probably overkill avoidance of explicit TUV referencing
-#
-function old_school_crypto {
-    echo "$@" | tr 'a-zA-Z' 'n-za-mN-ZA-M'
 }
 
 
@@ -199,7 +154,8 @@ if [ ! -d "${inputdir}" ]; then
 fi
 
 if [ -f "${output}" ]; then
-    die "output ${output} already exists"
+#    die "output ${output} already exists"
+    mv -f "${output}" "${output}.backup.${starttime}"
 fi
 
 tmpdir="/tmp/tmp.${progname}.xyz.${starttime}.$$"
diff --git a/tools/scripts/src-pkg-repo-diff b/tools/scripts/src-pkg-repo-diff
--- a/tools/scripts/src-pkg-repo-diff
+++ b/tools/scripts/src-pkg-repo-diff
@@ -3,9 +3,6 @@
 #############################################################################
 #############################################################################
 #
-# src-pkg-repo-diff--gen-debug-output (a second phase)
-#
-#
 # src-pkg-repo-diff generates a set of abbreviated comparisons of two 
 #                   related source package (src.rpm) repositories.
 #
@@ -37,11 +34,7 @@
 #############################################################################
 #############################################################################
 ##
-## src-pkg-repo-diff--gen-min-srpm-list \
-##     [<output_dir>=<input_right>.repo-diff/] \
-##     [<min_srpm_list>=<input_right>.repo-diff.srpm-list] \
-##     [[<input_left>=${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise/6Superset/en/os/SRPMS] \
-##     [<input_right>=${HOME}/.el-build/cache/build.ascendos.org___linux__ascendos__SRPMS]]
+## ...
 ##
 ##
 ## DESCRIPTION
@@ -65,14 +58,28 @@
 #############################################################################
 #############################################################################
 ##
-## get runtime environment
+## local constant definitions
 ##
-starttime="$( date +%Y-%m-%d--%H-%M-%S )"
-progname="$( basename $0 )"
-progdir=$( ( pushd $( dirname $( readlink -e $0 ) ) > /dev/null 2>&1 ; \
-    pwd ; popd > /dev/null 2>&1 ) )
-rundir="$( pwd )"
-mypid=$$
+
+# for common script library- libx.sh
+x_toolname="el-build"
+x_prefix=/usr
+
+
+#############################################################################
+#############################################################################
+##
+## load system library
+##
+
+if [ -f "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh" ]; then
+    source "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh"
+elif [ -f "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" ]; then 
+    source "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" 
+else
+    echo "$0: error: fatal: could not load ${x_toolname} system library libx.sh"
+    exit 1
+fi
 
 
 #############################################################################
@@ -81,11 +88,11 @@ mypid=$$
 ## constant and option default definitions
 ##
 
-# to enable debug messages
-debug=1
+# to enable debug messages if desired
+x_debug=0
 
-# to suppress status messages
-quiet=0
+# to suppress status messages if desired
+x_quiet=0
 
 
 #############################################################################
@@ -105,173 +112,6 @@ function usage {
 
 
 #############################################################################
-#
-# usage: status <message...>
-#
-# wrapper for sending status messages to console and log
-#
-# globals used: quiet, progname, logfiles(not required)
-#
-function status {
-    time="$( date +%Y-%m-%d.%H:%M:%S )"
-    if ((! $quiet)); then
-	echo "${progname}: ${time}: status: $@"
-    fi
-    for logfile in $logfiles; do
-	echo "${progname}: ${time}: status: $@" >> $logfile
-    done
-}
-
-#############################################################################
-#
-# usage: debug <message...>
-#
-# wrapper for sending debug messages to console and log
-#
-# globals used: debug, progname, logfiles(not required)
-#
-function debug {
-    time="$( date +%Y-%m-%d.%H:%M:%S )"
-    if (($debug)); then
-	echo "${progname}: ${time}: debug: $@"
-    fi
-    for logfile in $logfiles; do
-	echo "${progname}: ${time}: debug: $@" >> $logfile
-    done
-}
-
-
-#############################################################################
-#
-# usage: die <message...>
-#
-# issue last words
-#
-function die {
-    status "$@"
-    exit 1
-}
-
-
-#############################################################################
-#
-# usage: listremove "item" "list"
-#
-# return a list copy but with an item taken out
-#
-function listremove {
-    item="${1}"
-    shift
-
-    for word in ${@}; do
-	if [ "${word}" != "${item}" ]; then
-	    echo -en "${word} "
-	fi
-    done
-}
-
-
-#############################################################################
-#
-# usage: listin "item" "list"
-#
-# return true if item is in list
-#
-function listin {
-    item="${1}"
-    shift
-
-    retval=false
-    for word in "$@"; do
-	if [ "${word}" == "${item}" ]; then
-	    return 0;
-	fi
-    done
-    return 1
-}
-
-
-#############################################################################
-#
-# usage: listreverse "list"
-#
-# returns a given list of words reversed
-#
-function listreverse {
-    numwords=0
-    for word in $@; do
-	numwords=$(( ${numwords} + 1 ))
-	wordlist[${numwords}]="${word}"
-    done
-    for (( i=numwords ; ${i} > 0 ; i=$(( ${i} - 1 )) )); do
-	echo "${wordlist[${i}]}"
-    done
-}
-
-
-#############################################################################
-#
-# usage: get_asc_version <some-version.asc[.ASCVERSION].src.rpm>
-#
-# dies if input is not a proper .asc[.ASCVERSION].src.rpm, and returns
-# ASCVERSION, or the special 0 value for no suffixed version
-#
-function get_asc_version {
-    if ( echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
-	echo 0
-    elif ( ! echo "$@" | grep -q "\.asc\.[0-9]*\.src\.rpm$" ); then
-	die "no asc version because $@ is not a .asc.*src.rpm"
-    else
-	echo "$@" | sed -e 's/.*\.asc\.\([0-9]*\)\.src\.rpm$/\1/'
-    fi
-}
-
-
-#############################################################################
-#
-# usage: set_asc_version <version> <some-version.asc[.ASCVERSION].src.rpm>
-#
-# returns the given asc style package name, but with alternate version
-#
-function set_asc_version {
-    version="${1}"
-    shift
-
-    if ( ! echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
-	if ( ! echo "$@" | grep -q "\.asc\.[0-9]\+\.src\.rpm$" ); then
-	    die "set_asc_version: non-well-formatted asc src rpm file: $@"
-	fi
-    fi
-
-    if ((!${version})); then
-	if ( echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
-	    # in this case, return the same as the input
-	    echo "$@"
-	else 
-	    echo "$@" | sed -e "s/\.asc\.[0-9]\+\.src\.rpm\$/\.asc\.src\.rpm/"
-	fi
-    else
-	if ( echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
-	    echo "$@" | sed -e "s/\.asc\.src\.rpm\$/\.asc\.${version}\.src\.rpm/"
-	else
-	    echo "$@" | sed -e "s/\.asc\.[0-9]\+\.src\.rpm\$/\.asc\.${version}\.src\.rpm/"
-	fi
-    fi
-}
-
-
-#############################################################################
-#
-# usage: old_school_crypto <string>
-#
-# probably overkill avoidance of explicit TUV referencing
-#
-function old_school_crypto {
-    echo "$@" | tr 'a-zA-Z' 'n-za-mN-ZA-M'
-}
-
-
-#############################################################################
 #############################################################################
 ##
 ## main
@@ -279,11 +119,6 @@ function old_school_crypto {
 
 status "initializing..."
 
-
-#############################################################################
-### calculate tree root and set up environment
-elbuild_devroot=$( pushd "${progdir}/../.." > /dev/null 2>&1 ; \
-    pwd ; popd > /dev/null 2>&1 )
 
 
 #############################################################################
@@ -608,6 +443,3 @@ debug "goodbye..."
 #############################################################################
 #
 # ...
-
-
-
